<?php

abstract class RouterConfig {
  const ADMIN_USER_MOBILE_CHECK = '/account/admin/v1/mobileCheck';
  const ADMIN_ADD_USER = '/account/admin/v1/addUser';
  const ADMIN_USER_LOGIN = '/account/admin/v1/login';
  const ADMIN_USER_LOGOUT = '/account/admin/v1/logout';
  const ADMIN_USER_INFO = '/account/admin/v1/userInfo';
  const ADMIN_USER_LIST = '/account/admin/v1/userList';
  const ADMIN_SET_USER_STATUS = '/account/admin/v1/setUserStatus';
  const ADMIN_SET_USER_INFO = '/account/admin/v1/setUserInfo';
  const ADMIN_USER_RESET_PASSWORD = '/account/admin/v1/resetPassword';
  const ADMIN_USER_MENU = '/account/admin/v1/userMenu';
  const WEB_USER_MOBILE_CHECK = '/account/web/v1/mobileCheck';
  const WEB_USER_REGISTER = '/account/web/v1/register';
  const WEB_USER_LOGIN = '/account/web/v1/login';
  const WEB_USER_LOGOUT = '/account/web/v1/logout';
  const WEB_USER_INFO = '/account/web/v1/userInfo';
  const WEB_USER_RESET_PASSWORD = '/account/web/v1/resetPassword';
  const WEB_USER_CHANGE_PASSWORD = '/account/web/v1/changePassword';
  const WEB_USER_CHANGE_MOBILE = '/account/web/v1/changeMobile';
  const WEB_USER_INFO_MORE = '/account/web/v1/userInfoMore';
  const WEB_USER_CHILD_INFO = '/account/web/v1/childInfo';
  const STORY_BASE = '/story/v1/baseinfo';
  const STORY_BASE_SET = '/story/v1/baseinfoSet';
  const SONG_BASE = '/song/v1/baseinfo';
  const SONG_BASE_SET = '/song/v1/baseinfoSet';
  const WORD_CATEGORY = '/word/v1/category';
  const WORD_CATEGORY_SET = '/word/v1/categorySet';
  const WORD_BASE = '/word/v1/baseinfo';
  const WORD_BASE_SET = '/word/v1/baseinfoSet';
  const COURSE_BASE = 'course/v1/baseinfo';
  const COURSR_BASE_SET = 'course/v1/baseinfoSet';
  const ACTIVITY_BASE = 'activity/v1/baseinfo';
  const ACTIVITY_BASE_SET = 'activity/v1/baseinfoSet';
  const UPLOAD_PIC = '/general/uploadpicture';
  const UPLOAD_FILE = '/general/uploadfile';
  const SUGGESTION = '/general/suggestion';
  const DOWNLOAD_FILE = '/general/downloadfile';
  const SEARCH = '/general/search';
  const RELATED_SEARCH = '/general/relatedSearch';
  const EXACT_SEARCH = '/general/exactSearch';
  const WEB_USER_SEND_SMS = '/general/sendSMS';
  const WEB_USER_VERIFY_SMS = '/general/verifySMS';
  const WEB_USER_SEND_IMAGE_CODE = '/general/sendImageVerifyCode';
  const WEB_USER_VERIFY_IMAGE_CODE = '/general/checkImageVerifyCode';
  const BAIDU_TTS = '/thirdparty/baidu/tts';
  const APP_BASE = '/app/baseinfo';
  const CONTENT_BASE = '/content/baseinfo';
  const AUTH_MENU = '/auth/menu';
  const AUTH_ACTION = '/auth/action';
  const AUTH_USER_GROUP = '/auth/usergroup';
}

abstract class RouterMap {
  public static $router = array(
    RouterConfig::ADMIN_USER_MOBILE_CHECK => 'account/admin/v1/mobileCheckController',
    RouterConfig::ADMIN_ADD_USER => 'account/admin/v1/addUserController',
    RouterConfig::ADMIN_USER_LOGIN => 'account/admin/v1/LoginController',
    RouterConfig::ADMIN_USER_LOGOUT => 'account/admin/v1/LogoutController',
    RouterConfig::ADMIN_USER_INFO => 'account/admin/v1/userInfoController',
    RouterConfig::ADMIN_USER_LIST => 'account/admin/v1/userListController',
    RouterConfig::ADMIN_SET_USER_STATUS => 'account/admin/v1/setUserStatusController',
    RouterConfig::ADMIN_SET_USER_INFO => 'account/admin/v1/setUserInfoController',
    RouterConfig::ADMIN_USER_RESET_PASSWORD => 'account/admin/v1/resetPasswordController',
    RouterConfig::ADMIN_USER_MENU => 'account/admin/v1/userMenuController',
    RouterConfig::WEB_USER_MOBILE_CHECK => 'account/web/v1/mobileCheckController',
    RouterConfig::WEB_USER_REGISTER => 'account/web/v1/RegisterController',
    RouterConfig::WEB_USER_LOGIN => 'account/web/v1/LoginController',
    RouterConfig::WEB_USER_LOGOUT => 'account/web/v1/LogoutController',
    RouterConfig::WEB_USER_INFO => 'account/web/v1/userInfoController',
    RouterConfig::WEB_USER_RESET_PASSWORD => 'account/web/v1/resetPasswordController',
    RouterConfig::WEB_USER_CHANGE_PASSWORD => 'account/web/v1/changePasswordController',
    RouterConfig::WEB_USER_CHANGE_MOBILE => 'account/web/v1/changeMobileController',
    RouterConfig::WEB_USER_INFO_MORE => 'account/web/v1/userInfoMoreController',
    RouterConfig::WEB_USER_CHILD_INFO => 'account/web/v1/childInfoController',
    RouterConfig::STORY_BASE => 'story/v1/storyBaseInfoController',
    RouterConfig::STORY_BASE_SET => 'story/v1/storyBaseInfoSetController',
    RouterConfig::SONG_BASE => 'song/v1/songBaseInfoController',
    RouterConfig::SONG_BASE_SET => 'song/v1/songBaseInfoSetController',
    RouterConfig::WORD_CATEGORY => 'word/v1/wordCategoryController',
    RouterConfig::WORD_CATEGORY_SET => 'word/v1/wordCategorySetController',
    RouterConfig::WORD_BASE => 'word/v1/wordBaseInfoController',
    RouterConfig::WORD_BASE_SET => 'word/v1/wordBaseInfoSetController',
    RouterConfig::COURSE_BASE => 'course/v1/courseBaseInfoController',
    RouterConfig::COURSR_BASE_SET => 'course/v1/courseBaseInfoSetController',
    RouterConfig::ACTIVITY_BASE => 'activity/v1/activityBaseInfoController',
    RouterConfig::ACTIVITY_BASE_SET => 'activity/v1/activityBaseInfoSetController',
    RouterConfig::UPLOAD_PIC => 'general/UploadPictureController',
    RouterConfig::UPLOAD_FILE => 'general/UploadFileController',
    RouterConfig::SUGGESTION => 'general/suggestionController',
    RouterConfig::DOWNLOAD_FILE => 'general/downloadFileController',
    RouterConfig::SEARCH => 'general/searchController',
    RouterConfig::RELATED_SEARCH => 'general/relatedSearchController',
    RouterConfig::EXACT_SEARCH => 'general/exactSearchController',
    RouterConfig::WEB_USER_SEND_SMS => 'general/sendSMSController',
    RouterConfig::WEB_USER_VERIFY_SMS => 'general/verifySMSController',
    RouterConfig::WEB_USER_SEND_IMAGE_CODE => 'general/sendImageVerifyCodeController',
    RouterConfig::WEB_USER_VERIFY_IMAGE_CODE => 'general/checkImageVerifyCodeController',
    RouterConfig::BAIDU_TTS => 'thirdparty/baidu/ttsController',
    RouterConfig::APP_BASE => 'app/appBaseInfoController',
    RouterConfig::CONTENT_BASE => 'content/contentBaseInfoController',
    RouterConfig::AUTH_MENU => 'auth/menuController',
    RouterConfig::AUTH_ACTION => 'auth/actionController',
    RouterConfig::AUTH_USER_GROUP => 'auth/usergroupController'
  );
}
